function getCommonWords() {
  // Array de palavras comuns
  return [
    'Maçã',
    'Carro',
    'Casa',
    'Computador',
    'Gato',
    'Bicicleta',
    'Livro',
    'Piano',
    'Avião',
    'Violino',
    'Gelado',
    'Praia',
    'Leão',
    'Girafa',
    'Família',
    'Futebol',
    'Bikini',
    'Palhaço',
    'Lâmpada',
    'Árvore',
    'Peixe',
    'Borboleta',
    'Barco',
    'Cidade',
    'Relógio',
    'Escada',
    'Arco-íris',
    'Castelo',
    'Robô',
    'Elefante',
    'Mapa do tesouro',
    'Dragão',
    'Extraterrestre',
    'Ponte',
    'Labirinto',
    'Samurai',
    'Sereia',
  ];
}
